### PR TITLE
fix: shared data on different processes

### LINKED ISSUE #24: Node stats are lost when using different firefox tabs
As Firefox has a different process per tab, when running the service worker gateway and using different tabs, the stats context is not shared among them.

Accordingly, the **stats** data should be persisted (for instance in index db).

### PR DESCRIPTION
**Pull request by vasco-santos**
Added indexeddb datastore for storing the stats page data. This aims to allow users in Firefox to use different tabs to check the stats page.

A refactor to the tests was also made.

In the context of [ipfs/js.ipfs.io#207](https://github.com/ipfs/js.ipfs.io/issues/207)

Closes #24

### CODE REVIEW

**Review by fsdiogo — APPROVED** [review]
LGTM!

File: src/index.js [hunk 1]
```diff
@@ -3,47 +3,49 @@
...
+
+          fetchedCIDs.push({
+            cid: ipfsPath.split('/ipfs/')[1],
+            date: getFormattedDate(d),
+            time: getFormattedTime(d)
+          })
+
+          return set('fetched-cids', fetchedCIDs).then(() => resp)
+        })
     })
```
Comment (PedroMiguelSS) [inline src/index.js:35]: Add a `.catch()` here to handle the error.

**Review by PedroMiguelSS — CHANGES_REQUESTED** [review]

**Review by PedroMiguelSS — APPROVED** [review]
