### PR TITLE
fix: move stats page to the root

### LINKED ISSUE #15: Move stats page to the root
Stats page should be provided in /stats instead of /ipfs/stats

### PR DESCRIPTION
**Pull request by vasco-santos**
Closes #15

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -53,12 +53,12 @@ self.addEventListener('fetch', (event) => {
...
 
   // Not intercepting path
-  if (!path.startsWith(`${self.location.origin}/ipfs`)) {
+  if (!(path.startsWith(`${self.location.origin}/ipfs`) || path.startsWith(`${self.location.origin}/stats`))) {
     return
   }
 
   // Stats Page
-  if (path.startsWith(`${self.location.origin}/ipfs/stats`)) {
+  if (path.startsWith(`${self.location.origin}/stats`)) {
```
Comment (fsdiogo) [inline src/index.js]: You could create a variable like `isStatsPath` to minimise the conditionals.

File: test/stats-view.spec.js [hunk 2]
```diff
@@ -24,15 +24,17 @@ describe('Stats view page', function () {
...
     require('../src')
 
-    return Promise.all([self.trigger('fetch', new Request(`/ipfs/QmT78zSuBmuS4z925WZfrqQ1qHaJ56DQaTfyMUF7F8ff5o`)),
+    Promise.all([self.trigger('fetch', new Request(`/ipfs/QmT78zSuBmuS4z925WZfrqQ1qHaJ56DQaTfyMUF7F8ff5o`)),
       self.trigger('fetch', new Request(`/ipfs/QmYwAPJzv5CZsnA625s3Xf2nemtYgPpHdWEz79ojWnPbdG`)),
       self.trigger('fetch', new Request(`/ipfs/QmYwAPJzv5CZsnA625s3Xf2nemtYgPpHdWEz79ojWnPbdG/about`))])
       .then((values) => {
         expect(values).to.exist()
-        return self.trigger('fetch', new Request(`/ipfs/stats`))
+        return self.trigger('fetch', new Request(`/stats`))
```
Comment (fsdiogo) [inline test/stats-view.spec.js]: Remove the `return` keyword.

**Review by fsdiogo — CHANGES_REQUESTED** [review]
Don't forget to fix the linting errors!

**Review by fsdiogo — APPROVED** [review]

**Review by PedroMiguelSS — APPROVED** [review]
